export default [
  {
    id: '1',
    name: 'Toad',
    url: 'https://cdn.icon-icons.com/icons2/3797/PNG/512/toad_super_mario_bros_icon_232934.png',
    desc: 'Toad (Kinopio en japonés) es un personaje de la saga de videojuegos de Mario de Nintendo. Es un pequeño humanoide con un gorro en la cabeza en forma de champiñón blanco con puntos rojos como se ve en la serie de Súper Mario Bros 3. Son personas pacíficas del Reino Champiñón. Al igual que otros personajes de Mario, como Yoshi, tanto la especie como el individuo principal se llaman Toad. Aparecieron por primera vez en Super Mario Bros., donde decían la famosa frase "Gracias Mario/Luigi, pero la princesa está en otro castillo" cada vez que Mario llegaba al final de los primeros siete castillos. En Paper Mario aparece la ciudad Toad, capital del Reino Champiñón, donde residen los Toads llamados "gente champiñón."',
  },
  {
    id: '2',
    name: 'Super Luigi',
    url: '',
    desc: '',
  },
  {
    id: '3',
    name: 'Super Mario',
    url: 'https://cdn.icon-icons.com/icons2/3797/PNG/512/mario_super_bros_icon_232936.png',
    desc: ' ario (マリオ) es el protagonista de la serie de videojuegos Super Mario y la mascota de Nintendo. Fue creado por Shigeru Miyamoto en 1981 e hizo su primera aparición en el videojuego arcade Donkey Kong. Es un fontanero estadounidense de origen italiano que actualmente vive en el Reino Champiñón. Como el héroe que es, se encarga de salvar a la gente, especialmente a la Princesa Peach, a quien ha salvado muchísimas veces de las garras del temible Bowser, quien es su archi-enemigo. Es una persona humilde y de buen corazón, que no le importa cuanto tenga que recorrer para salvar a la gente que necesita su ayuda. ',
  },
  {
    id: '4',
    name: 'Bowser',
    url: 'https://i.imgur.com/II0QRbF.png',
    desc: 'Bowser (クッパ, Kuppa en Japón) es el villano principal de la franquicia de Super Mario Bros. y el más icónico de los videojuegos. Hizo su debut en Super Mario Bros. y desde entonces ha aparecido en la inmensa mayoría de juegos de la saga. Es el Rey de los Koopas y vive en un enorme y peligroso castillo en el Reino Koopa. El objetivo de Bowser en la mayoría de juegos es secuestrar a la Princesa Peach, de la que está enamorado, y dominar el Reino Champiñón, aunque sus planes siempre son arruinados por Mario. Bowser tiene un hijo llamado Bowser Jr (Bowsy en España), que sigue los pasos de su padre y le ayuda a secuestrar a la Princesa Peach y a luchar contra Mario. Además, Bowser muchas veces aparece acompañado de sus 7 secuaces, los Koopalings. Para cumplir sus objetivos, Bowser tiene un enorme y variado ejército de leales esbirros. La armada de Bowser está compuesta por los Goombas, Koopa Troopa, Hermanos Martillo, Plantas Piraña, Chomp Cadenas, Pinchones, Buzzy Beetles, Lakitus, Cheep Cheeps, Bloopers, Rocas Picudas, Bob-ombs, Magikoopas, Shy Guys, Huesitos y muchos otros enemigos más. Pese a que suele presentarse como un villano despiadado en la Saga Super Mario, en los spin-offs se demuestra que Bowser en realidad es algo torpe y que en el fondo tiene buen corazón, además de que demuestra no ser muy inteligente y a menudo es engañado por otros villanos. En los juegos de la saga principal, Bowser nunca ha sido personaje jugable (Sin contar cuando es controlado por Mario en Super Mario Odyssey). Por su parte, en los spin-offs Bowser sí ha aparecido como personaje jugable en una gran cantidad de juegos, apareciendo en casi todos los juegos de la s',
  },
  {
    id: '5',
    name: 'Peach',
    url: 'https://cdn.icon-icons.com/icons2/3797/PNG/512/peach_princess_super_mario_bros_icon_232944.png',
    desc: 'La Princesa Peach o Princesa Toadstool es la princesa del Reino Champiñón. Apareció por primera vez en Super Mario Bros. para NES. Peach fue creada por Shigeru Miyamoto y es la damisela en apuros en la mayoría de los juegos de Mario. Desde su debut en Super Mario Bros., Peach ha aparecido en casi todos los juegos de la franquicia, volviéndose uno de los iconos más conocidos de los videojuegos y el personaje femenino de los videojuegos más conocido del mundo. En los juegos de la saga Super Mario, Peach sólo ha sido jugable en Super Mario Bros. 2 y en Super Mario 3D World. Sin embargo, ella ha sido jugable en muchos de los spin offs de la franquicia, siendo jugable en todos los juegos de Mario Kart, de Mario party, en todos los Mario Tennis, Mario golf, Mario Strikers y Mario Baseball, entre muchos otros juegos. Ella también ha aparecido como personaje jugable en Super Smash Bros. Melee, Super Smash Bros. Brawl, Super Smash Bros. para Nintendo 3DS/WiiU, Super Smash Bros. Ultimate y en todos los juegos de Mario & Sonic en los Juegos Olímpicos entre muchos otros juegos.',
  },
  {
    id: '6',
    name: 'Luigi',
    url: '',
    desc: '',
  },
  {
    id: '7',
    name: 'Mario',
    url: '',
    desc: '',
  },
  {
    id: '8',
    name: 'Goomba',
    url: 'https://cdn.icon-icons.com/icons2/3797/PNG/512/goomba_super_mario_bros_icon_232943.png',
    desc: 'Los Goombas (クリボー Kuribō en japonés) son unos enemigos que hicieron su debut en Super Mario Bros. y desde entonces han aparecido en la mayoría de juegos de la franquicia, siendo Super Mario Bros. 2 y Super Mario Sunshine los únicos juegos de la saga principal en donde no aparece ningún Goomba. Los Goombas son posiblemente los enemigos más icónicos de la saga y son uno de los enemigos más conocidos de los videojuegos. Ellos tienen el papel de ser típico enemigo que aparece al inicio de la aventura y es muy fácil de derrotar. Al igual que los Toads, los Goombas están basados en hongos, específicamente en una especie de Asia Oriental llamada seta Shiitake (También conocida como seta china)Antiguamente, los Goombas vivían en el Reino Champiñón, donde convivían con los Toads pacíficamente. No obstante, luego de que Bowser y su ejército de Koopas atacaran el reino, los Goombas decidieron unirse a las filas de Bowser y traicionar el reino, siendo conocidos desde entonces como traidores. En los juegos de plataformas 2D, su estrategia de ataque consiste en simplemente andar de derecha a izquierda esperando chocarse con Mario, mientras que en los juegos de plataformas 3D persiguen a Mario.',
  },
  {
    id: '9',
    name: 'Koopa Para-Troopa',
    url: '',
    desc: '',
  },
  {
    id: '10',
    name: 'Bullet Bill',
    url: '',
    desc: '',
  },
  {
    id: '11',
    name: 'Buzzy Beetle',
    url: '',
    desc: '',
  },
  {
    id: '12',
    name: 'Blooper',
    url: '',
    desc: '',
  },
  {
    id: '13',
    name: 'Hammer Bro',
    url: 'https://cdn.icon-icons.com/icons2/3797/PNG/512/hammer_bro_super_mario_bros_icon_232939.png',
    desc: 'Los Hermanos Martillo (Hammer Bros. en inglés) son unos enemigos que hicieron su debut en el videojuego Super Mario Bros. para Nintendo Entertainment System y que desde entonces han seguido apareciendo de forma recurrente en la franquicia. Suelen aparecer en parejas y atacan lanzando martillos a los protagonistas, de ahí su nombre. Los Hermanos Martillos tienen un mucho cariño a sus martillos e incluso los tratan como si tuvieran vida propia como se ve en Super Mario RPG: La Leyenda de las Siete Estrellas. Los principales ejércitos de Bowser están formados por Hermanos Martillos, ya que estos son guerreros más adeptos que los Goombas y los Koopas. Ellos fueron diseñados originalmente por Kazuaki Marita.',
  },
  {
    id: '14',
    name: 'Cheep Cheep',
    url: 'https://cdn.icon-icons.com/icons2/3797/PNG/512/fish_cheep_super_mario_bros_icon_232935.png',
    desc: 'Los Cheep Cheeps son unos enemigos recurrentes en la franquicia que hicieron su primera aparición en Super Mario Bros. como enemigos. Estos peces han aparecido en la gran mayoría de juegos de la franquicia. Son los enemigos más comunes e icónicos de los niveles acuáticos de los juegos de Mario. Suelen nadar en grandes grupos junto a otros Cheep Cheeps u otros enemigos acuáticos, como los Bloopers. Aparentemente pueden vivir en cualquier tipo de agua, incluso aguas a muy bajas temperaturas o aguas contaminadas.',
  },
  {
    id: '15',
    name: 'Koopa Troopa',
    url: 'https://cdn.icon-icons.com/icons2/3797/PNG/512/turtle_koopa_super_mario_bros_icon_232948.png',
    desc: 'Koopa (ノコノコ nokonoko en japonés, pronunciado como Kupa) es el segundo enemigo más común en la saga de Mario después de los Goombas. Es una clase de especies conocidas por su apariencia de tortuga. Hay muchas variedades de Koopas, los más comunes son los Koopa Troopa, quienes regularmente son denominados Koopas por ser comunes. El líder de los Koopas es Bowser, quien es también el líder del conjunto: la Tropa Koopa, una organización que ha planeado conquistar al pacífico Reino Champiñón, múltiples veces. Muchos Koopas son también soldados de este ejército, y tienen diferentes puestos en la organización basados en las habilidades de cada especie. Por ejemplo, los Koopa Troopas no tienen atributos especiales, son normalmente asignados como básicos soldados de infantería de la Tropa Koopa. En Super Mario Bros. 3, si aprietas el botón de correr, podrás agarrar su caparazón y lanzarlo, así obteniendo puntaje por cada enemigo, y si hay muchos podrás conseguir una vida.    ',
  },
  {
    id: '16',
    name: 'Spiny',
    url: '',
    desc: '',
  },
  {
    id: '17',
    name: '1-Up Mushroom',
    url: '',
    desc: '',
  },
  {
    id: '18',
    name: 'Koopa Troopa',
    url: 'https://cdn.icon-icons.com/icons2/3797/PNG/512/turtle_koopa_super_mario_bros_icon_232947.png',
    desc: 'Koopa Troopa es una de las especies amigas en la serie de videojuegos de Mario de Nintendo. Son tortugas, y es el más común de los Koopa. Los Koopa Troopa son los efectivos estándar del Ejército Koopa que trabaja para Peach. Como son el más bajo rango de los miembros del Ejército Koopa, sólo patrullan a pie sus zonas asignadas. Los Koopa Troopa aparecen por primera vez en el juego de arcade Mario Bros. bajo el nombre de "Shellcreepers". En Super Mario Bros., se rebautizaron como "Koopa Troopa". Pueden ser utilizadas sus conchas como proyectiles después de que se escondieran ahí por que Mario saltó sobre ellas. Super Mario World trajo cambios drásticos a los Koopa Troopa, alterando su forma de caminar (sobre dos piernas y usando zapatos). Paper Mario 64 y Paper Mario: La Puerta Milenaria introducen Koopas amistosos que tienen sus propias ciudades, e incluso son rescatados por Mario en varias ocasiones. Los Koopa Troopa genéricos también han aparecido en toda la saga de Mario Party como personajes no jugables. Los Koopa Troopas únicamente han sido jugables en los juegos de Mario Kart y otros juegos de deporte junto con Paratroopas. Mario ha ayudado mucho a los Koopa Troopas como en Mario Party 8 cuándo un Koopa le da unas monedas si él encuentra las cosas que un ladrón le ha robado.',
  },
  {
    id: '19',
    name: 'Lava Bubble',
    url: '',
    desc: '',
  },
  {
    id: '20',
    name: 'Cloud',
    url: '',
    desc: '',
  },
  {
    id: '21',
    name: 'Lakitu',
    url: 'https://cdn.icon-icons.com/icons2/3797/PNG/512/lakitu_super_mario_bros_icon_232945.png',
    desc: 'Los Lakitus (ジュゲム, Jugemu en Japonés) son unos enemigos que hicieron su debut en Super Mario Bros. Y desde su primera aparición se han vuelto enemigos comunes en la saga. Ellos siempre van acompañados de su nube, sobre la que surcan los cielos y desde donde lanzan huevos de Pinchones, de los que salen Pinchones cuando caen al suelo. Sin su nube aparentemente son incapaces de moverse, pese a tener piernas.',
  },
  {
    id: '22',
    name: 'Flower Mario',
    url: 'https://cdn.icon-icons.com/icons2/3797/PNG/512/flower_mario_power_super_bros_icon_232941.png',
    desc: 'La Flor de fuego (Fire Flower o Flame Flower en inglés) es un ítem de la saga Super Mario. La Flor de Juego hizo su primera aparición en Super Mario Bros., y desde su debut ha seguido apareciendo en numerosos juegos de la saga, convirtiéndose en uno de los ítems más icónicos de la saga. La Flor de fuego otorga el poder del fuego a aquellos que la tocan, permitiéndoles lanzar bolas de fuego que pueden chamuscar y derrotar con fácilidad a muchos enemigos. Las bolas de fuego también pueden derretir el hielo e iluminar un poco lugares oscuros. Sin embargo, no pueden destruir bloques, al contrario que otros proyectiles como los caparazones de los Koopas. Las bolas de fuego sin lo suficientemente resistente para no con el agua, siendo posible disparar bolas de fuego bajo el agua en casi todos los juegos de la saga principal (A excepción de en Super Mario Galaxy y Super Mario Galaxy 2). Las Flores de Fuego comúnmente se encuentran en el interior de bloques ?. Al contrario que los champiñones, las flores de fuego no se mueven tras salir de éstos.',
  },
  {
    id: '23',
    name: '? Block',
    url: '',
    desc: '',
  },
  {
    id: '24',
    name: 'Goomba Lava',
    url: 'https://cdn.icon-icons.com/icons2/3797/PNG/512/goomba_super_mario_bros_icon_232940.png',
    desc: 'Los Goombas hacen su primera aparición en Super Mario Bros., apareciendo en una gran cantidad de niveles. Los Goombas son los enemigos más fáciles de derrotar del juego y también son los menos peligrosos. Se limitan a caminar por los niveles, esperando chocarse con Mario en el proceso. Pueden derrotarse con cualquier ataque. Una vez que se supera el juego, todos los Goombas de los niveles son sustituidos por Buzzy Beetles. Luego de su debut ellos reaparecerían en Super Mario Bros.: The Lost Levels, donde tendrían las mismas características que en Super Mario Bros.',
  },
  {
    id: '25',
    name: 'Goomba Night',
    url: 'https://cdn.icon-icons.com/icons2/3797/PNG/512/goomba_super_mario_bros_icon_232938.png',
    desc: 'En Super Mario Bros. 3, los Goombas reaparecen como enemigos. Al igual que en Super Mario Bros., caminan por los niveles y pueden vencerse con cualquier tipo de ataque. Este juego introduce Sub-especies de algunos enemigos ya existentes, siendo los Goombas uno de estos: Los Paragoombas son Goombas que vuelan sobre Mario y le lanzan Micro-Goombas. Los Micro-Goombas son Goombas de un tamaño muy pequeños. Éstos se adhieren a Mario y evitan que salte alto. Los Goombas Gigantes son Goombas de gran tamaño, pero pueden ser derrotados del mismo modo que los Goombas regulares; Y los Paragoombas Rojos, que son Paragoombas que pese a tener alas, no puede volar, aunque pueden saltar un poco y persiguen a Mario.',
  },
];
